### ISSUE TITLE
No Readme

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/syft-translator.js#9]
This project currently lacks a readme for contributors and users to understand what is going on

**Comment by rohit1576** [comment]
@robert-wagner Can you assign me to this issue?

**Comment by robert-wagner** [comment]
Sure! I currently am finishing up a first draft of it right now. it will be pushed to the readme_update branch in a few minutes

**Comment by robert-wagner** [comment]
As it turns out, I am unable to assign it to you as you are not a member of the openMined organization.
